# Generated by Django 3.2.14 on 2022-09-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productfeatures_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_set', to='products.productfeature'),
        ),
    ]
