# Generated by Django 3.2.14 on 2022-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='featur_1',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='featur_2',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='featur_3',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='featur_4',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='featur_5',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='product',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='title',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='feature_set', to='products.ProductFeature'),
        ),
    ]
